Repository YodaGrammar/kelp, pull requests merged in 2018-07, with the labels that each got.

#121 clean of the code
  src/Controller/PackagingController.php
  src/Controller/ProductController.php
  src/Controller/RegistrationController.php
  src/Controller/StorageController.php
  src/Controller/TypeStorageController.php
  src/Entity/EntityTrait.php
  src/Entity/Storage.php
  src/Factory/Entity/PackagingFactory.php
  src/Factory/Entity/ProductFactory.php
  src/Factory/Entity/StorageFactory.php
  src/Factory/Entity/TypeStorageFactory.php
  src/Form/Filter/FilterProductType.php
  src/Form/UserType.php
  src/FormHandler/Filter/PackagingFilterFormHandler.php
  src/FormHandler/Filter/ProductFilterFormHandler.php
  src/FormHandler/Filter/TypeStorageFilterFormHandler.php
  src/FormHandler/PackagingFormHandler.php
  src/FormHandler/ProductFormHandler.php
  src/FormHandler/StorageFormHandler.php
  src/Migrations/Version20180423201649.php
Labels: enhancement

#124 end crud packaging
  config/routes/packaging.yml
  src/Controller/PackagingController.php
  src/FormHandler/PackagingFormHandler.php
  src/FormHandler/ProductFormHandler.php
  src/Migrations/Version20180423201649.php
  src/Repository/PackagingRepository.php
  src/Repository/StorageRepository.php
  templates/packaging/list.html.twig
  templates/storage/list.html.twig
  translations/messages.fr.yml
Labels: enhancement

#125 Improve docker and remove legacy docker image
  Makefile
  docker-compose.yml
  docker/nginx.conf
  docker/nginx/site.conf
  docker/php/Dockerfile
Labels: enhancement

#128 hotfix prod
  src/Controller/RegistrationController.php
  src/DTO/UserDTO.php
  src/Form/UserType.php
  templates/registration/register.html.twig
  translations/messages.fr.yml
Labels: bug

#143 amelioration homepage
  templates/base.offline.html.twig
  templates/nav.html.twig
Labels: enhancement

#145 debug pager et routing product list
  config/routes/product.yml
  src/FormHandler/Filter/ProductFilterFormHandler.php
Labels: bug

#138 Delete dto refactoring repository product
  config/routes/packaging.yml
  config/routes/product.yml
  config/routes/storage.yaml
  src/Controller/ProductController.php
  src/DTO/ProductDTO.php
  src/Entity/Product.php
  src/Factory/DTO/ProductDTOFactory.php
  src/Factory/Entity/EntityFactoryInterface.php
  src/Factory/Entity/PackagingFactory.php
  src/Factory/Entity/ProductFactory.php
  src/Factory/Entity/StorageFactory.php
  src/Factory/Entity/TypeStorageFactory.php
  src/Form/ProductType.php
  src/FormHandler/ProductFormHandler.php
  src/Repository/ProductRepository.php
  templates/product/create.html.twig
  templates/product/edit.html.twig
  tests/Factory/Entity/ProductFactoryTest.php
  tests/FormHandler/ProductFormHandlerTest.php
Labels: Evolution

#147 debug packaging
  templates/packaging/form.html.twig
  translations/messages.fr.yml
Labels: bug

#146 Remove DTO and useless Factory
  features/Controller/Registration.feature
  src/Controller/PackagingController.php
  src/Controller/ProductController.php
  src/Controller/RegistrationController.php
  src/Controller/StorageController.php
  src/Controller/TypeStorageController.php
  src/DTO/PackagingDTO.php
  src/DTO/StorageDTO.php
  src/DTO/TypeStorageDTO.php
  src/DTO/UserDTO.php
  src/Entity/EntityTrait.php
  src/Entity/Packaging.php
  src/Entity/Product.php
  src/Entity/Storage.php
  src/Entity/TypeProduct.php
  src/Entity/TypeStorage.php
  src/Entity/User.php
  src/Factory/DTO/DTOFactoryInterface.php
  src/Factory/DTO/PackagingDTOFactory.php
  src/Factory/DTO/StorageDTOFactory.php
  src/Factory/DTO/UserDTOFactory.php
  src/Factory/Entity/EntityFactoryInterface.php
  src/Factory/Entity/PackagingFactory.php
  src/Factory/Entity/ProductFactory.php
  src/Factory/Entity/StorageFactory.php
  src/Factory/Entity/TypeStorageFactory.php
  src/Factory/PackagingFactory.php
  src/Factory/ProductFactory.php
  src/Factory/StorageFactory.php
  src/Factory/UserFactory.php
  src/Form/Handler/FormHandlerTrait.php
  src/Form/Handler/PackagingFormHandler.php
  src/Form/Handler/ProductFormHandler.php
  src/Form/Handler/RegistrationFormHandler.php
  src/Form/Handler/StorageFormHandler.php
  src/Form/PackagingType.php
  src/Form/ProductType.php
  src/Form/StorageType.php
  src/Form/TypeStorageType.php
  src/Form/UserType.php
  src/FormHandler/FormHandlerInterface.php
  src/FormHandler/StorageFormHandler.php
  src/Repository/EntityRepositoryInterface.php
  src/Repository/PackagingRepository.php
  src/Repository/ProductRepository.php
  src/Repository/StorageRepository.php
  src/Repository/UserRepository.php
  templates/product/list.html.twig
  tests/Factory/DTO/StorageDTOFactoryTest.php
  tests/Factory/DTO/UserDTOFactoryTest.php
  tests/Factory/Entity/ProductFactoryTest.php
  tests/FormHandler/PackagingFormHandlerTest.php
  tests/FormHandler/ProductFormHandlerTest.php
  tests/FormHandler/StorageFormHandlerTest.php
  translations/messages.fr.yml
Labels: enhancement

#155 Fix Expiration Date
  src/Migrations/Version20180726135652.php
Labels: bug
